services:
  fluentd:
    image: fluent/fluentd:v1.15-1
    user: root:root
    volumes:
      - type: bind
        source: ./fluentd/conf
        target: /fluentd/etc
      - type: bind
        source: ./fluentd/log
        target: /fluentd/log   
    ports:
      - 9880:9880
    command: "-c /fluentd/etc/fluent.conf"

  