services:
  fluentd:
    build: ./fluentd
    user: root:root
    volumes:
      - type: bind
        source: ./fluentd/conf
        target: /fluentd/etc
      - type: bind
        source: ./fluentd/log
        target: /fluentd/log   
    ports:
      - 9880:9880
    command: "-c /fluentd/etc/fluent.conf"

  minio:
    image: quay.io/minio/minio
    volumes:
      - type: volume
        source: minio-vol
        target: /data
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
    command: "server /data --console-address ':9090'"

volumes:
  minio-vol:

  